theme: jekyll-theme-minimal
title: Piyush Verma
description: Welcome to my web portfolio !! 

[Email](vermaph@mail.uc.edu) | [LinkedIn](https://www.linkedin.com/in/vermaph/) | [RPub](https://rpubs.com/vermaph) | [TableauPublic](https://public.tableau.com/profile/piyush.verma#!/) | [GitHub](https://github.com/vermaph/Codes) | [StackOverFlow](https://stackoverflow.com/users/story/5750741)
